### ISSUE TITLE
Please make it possible to read from the Systemd journal.

### ISSUE THREAD

**Issue by rnhurt** [aws/amazon-cloudwatch-agent#382]
Currently, the only way to get logging information out of Systemd services is to port the information to (r)syslog or use something like [Datadog's Vector product](https://vector.dev/blog/datadog-acquisition/).  However, it would be great if we could reference Systemd journal just like we do with log files.  

I propose that you add a new "logs" section named, `systemd`, as an addition to the existing `files` and `windows_events` sections.

**Comment by lwoggardner** [comment]
possibly related question.  Has anyone tried reading from journald using a named pipe to a journalctl process?

Either multiple named pipes for different subsets of the journal, or just one and use filtering on the cloudwatch agent side?

**Comment by MioG777829** [comment]
Important reference point - the Elastic Beanstalk AMIs which use AL2023 have rsyslog installed to create logs in the file system as it was before.  The EB team is working around this by keeping legacy configuration in place.  There is no firm AWS strategy (that is visible) to upgrade these approaches to extract information directly from systemd journal.

**Comment by rdkls** [comment]
I would've thought this would be very important feature for the agent; would think one of the most common use cases is someone spinning up an ec2 instance (now AL3 which uses only default journald) and wanting to easily get logs into CW. Is there a reason it's not?

**Comment by andreaswittig** [comment]
Would be so cool to be able to collect metrics from Amazon Linux 2023 with `amazon-cloudwatch-agent` as well.

**Comment by ozbillwang** [comment]
fixed with below commands, please make sure, when install CloudWatch Agent, it sets ACL on the folder itself , subfolders and files under the target folders.

set ACL to existing files and sub-folders
```
setfacl -R -m u:cwagent:r /var/log
```
and add ACL on folder /var/log, for any new files and subfolders created under it.
```
sudo setfacl -R -d u:cwagent:r /var/log
```

Not sure, why they can't be run with together with `-d ` and `-m`.

**Comment by grodriguezl** [comment]
It's incredible that this isn't solved for a fresh AL2023 and I need to use syslog or change systemd files. What's the point of removing syslog if the new solution can't be integrated with cloudwatch agent?

**Comment by cartwrightian** [comment]
Can someone make clearer on the documentation that cloud watch agent is not compatible with amazon linux 2023 if you want to see system logs, save folks wasting time googling etc and eventually ending up here.

**Comment by galoitsu** [comment]
In [the official documentation](https://docs.aws.amazon.com/linux/al2023/ug/journald.html)

> Although rsyslog is an optional package in AL2023, we recommend the new systemd based journalctl interface and related packages.

It seems a bit unkind that there is no official tool to replace it.

**Comment by gberenice** [comment]
Any updates on this one?

**Comment by DaveQB** [comment]
Bump?

**Comment by yourzinc** [comment]
Hello, as mentioned in the public documentation [[1]](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/deploy-container-insights-EKS.html):

```txt
We recommend using Amazon Linux 2 nodes for full compatibility when using the Amazon CloudWatch Observability Add-on. 
When using Amazon Linux 2023 nodes, dataplane and host logs vended by Container Insights will not be available by default due to the change in the system logging mechanism introduced in Amazon Linux 2023. 
Application logs will continue to work as expected. 
For more information about Amazon Linux 2023 changes, see the [Amazon Linux 2023 User Guide](https://docs.aws.amazon.com/linux/al2023/ug/journald.html).
```


A possible workaround for this issue is to install rsyslog on Amazon Linux 2023 [[2]](https://repost.aws/knowledge-center/ec2-linux-al2023-find-log-files):
```sh
dnf install rsyslog
systemctl enable rsyslog --now
```

After installation, you can use the CloudWatch Agent to collect logs from /var/log and send them to CloudWatch Logs.

**Comment by ghthor** [comment]
I think the modern solution is using [fluent-bit](https://github.com/fluent/fluent-bit). Took me a few mins to find this project, I hadn't heard of it. But the thought of running rsyslog just to ship logs to cloudwatch made me want to vomit.

Now, maybe configuing fluent-bit will also make me want to vomit, but we'll just have to see.

**Comment by robdew** [comment]
> Now, maybe configuing fluent-bit will also make me want to vomit, but we'll just have to see.

No it's pretty straightforward.  But even with a fair amount of knowledge configuring fluent-bit, I went with rsyslog forwarding because it keeps our cloudwatch agent configs a little cleaner.
